#pragma once
#include <stdint.h>
#include <math.h>

// These are used by the helpers below. Override in your build if needed.
#ifndef RPM_PER_HZ
#define RPM_PER_HZ 20.0f       // 3 pulses per rev => 60/3 = 20 RPM/Hz
#endif
#ifndef MPH_PER_HZ
#define MPH_PER_HZ 0.8425872f  // your measured/calibrated value
#endif

// LPTIM2 handle is generated by CubeMX
#ifdef __cplusplus
extern "C" {
#endif
extern LPTIM_HandleTypeDef hlptim2;
#ifdef __cplusplus
}
#endif

// Kernel clock for LPTIM2 after your /64 prescaler (64 MHz / 64 = 1 MHz)
#ifndef LPTIM2_KCLK_HZ
#define LPTIM2_KCLK_HZ 1000000UL
#endif

// Initialize LPTIM2 PWM on PA8 and start in a safe, low frequency
static inline void TachTest_Init(void)
{
  // Start at 10 Hz with ~50% duty
  const uint32_t fclk   = (uint32_t)LPTIM2_KCLK_HZ;
  uint32_t period_ticks = fclk / 10U;
  if (period_ticks < 2U)     period_ticks = 2U;
  if (period_ticks > 65535U) period_ticks = 65535U;

  // Start the PWM once; afterwards we only update ARR/CMP
  // Signature: HAL_LPTIM_PWM_Start(&hlptim2, LPTIM_CHANNEL_1, Period, Pulse)
  HAL_LPTIM_PWM_Start(&hlptim2,  period_ticks - 1U, (period_ticks - 1U) >> 1);
}

// Stop PWM if you need to relinquish the pin
static inline void TachTest_Stop(void)
{
  HAL_LPTIM_PWM_Stop(&hlptim2);
}

// Set raw frequency in Hz; updates ARR/CMP without stopping the timer.
// For hz <= ~0.1, it parks the output LOW by setting compare = 0.
static inline void TachTest_SetHz(float hz)
{
  const uint32_t fclk = (uint32_t)LPTIM2_KCLK_HZ;

  if (!(hz > 0.1f)) {
    __HAL_LPTIM_AUTORELOAD_SET(&hlptim2, 1U);   // minimal period
    __HAL_LPTIM_COMPARE_SET(&hlptim2, 0U);      // drives output low
    return;
  }

  // Compute period from frequency; clamp to 16-bit
  float period_f = (float)fclk / hz;
  uint32_t period = (period_f < 2.f) ? 2U : (period_f > 65535.f ? 65535U : (uint32_t)(period_f + 0.5f));

  // 50% duty
  uint32_t cmp = (period - 1U) >> 1;

  // Live update (no stop/start)
  __HAL_LPTIM_AUTORELOAD_SET(&hlptim2, period - 1U);
  __HAL_LPTIM_COMPARE_SET(&hlptim2, cmp);
}

// Convenience helpers if you want to specify in vehicle units
static inline void TachTest_SetFromRPM(float rpm)
{
  if (RPM_PER_HZ <= 0.0f) return;
  TachTest_SetHz(rpm / RPM_PER_HZ);
}

static inline void TachTest_SetFromMPH(float mph)
{
  if (MPH_PER_HZ <= 0.0f) return;
  TachTest_SetHz(mph / MPH_PER_HZ);
}
